--// ShiroGraphite, the in-game half of Shiro's Graphite skin.
--//
--// Generated by tools/gen-uiskins.mjs from src/styles/tokens/.
--// Every class Evolved defines is defined here, because a class this skin
--// omits falls through to `default`, whose inline draw functions crash on a
--// captioned control that carries noFont.

Spring.Echo("Shiro: ShiroGraphite skin.lua loaded from " .. tostring(SKINDIR))

local skin = {
	info = { name = "ShiroGraphite", version = "1.0", author = "Shiro" },
}

--// Merged into every control after its own class.
skin.general = {
	textColor       = {0.839, 0.839, 0.839, 1},
	borderColor     = {1, 1, 1, 0.15},
	disabledColor   = {0.369, 0.369, 0.369, 1},
	borderThickness = 1,
	font = {
		color   = {1, 1, 1, 1},
		size    = 13,
		outline = false,
		shadow  = false,
	},
}

skin.icons = {
	imageplaceholder = ":cl:placeholder.png",
}

skin.button = {
	TileImageArrow       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/arrow.png",
	padding              = {10, 10, 10, 10},
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	DrawControl          = DrawButton,
}

skin.button_hidden = {
	TileImageBK     = ":cl:empty.png",
	TileImageFG     = ":cl:empty.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	focusColor      = {0.132, 0.132, 0.132, 1},
	selectedColor   = {0.125, 0.125, 0.125, 1},
	DrawControl     = DrawButton,
}

skin.button_tiny = {
	TileImageArrow       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/arrow.png",
	padding              = {10, 10, 10, 10},
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	DrawControl          = DrawButton,
}

skin.overlay_button = {
	TileImageArrow       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/arrow.png",
	padding              = {10, 10, 10, 10},
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	DrawControl          = DrawButton,
}

skin.overlay_button_tiny = {
	TileImageArrow       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/arrow.png",
	padding              = {10, 10, 10, 10},
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	DrawControl          = DrawButton,
}

skin.button_square = {
	TileImageArrow       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/arrow.png",
	padding              = {10, 10, 10, 10},
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	DrawControl          = DrawButton,
}

skin.button_tab = {
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border_tab.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.051, 0.051, 0.051, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	padding              = {1, 1, 1, 2},
	DrawControl          = DrawButton,
}

skin.button_large = {
	TileImageArrow       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/arrow.png",
	padding              = {10, 10, 10, 10},
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	DrawControl          = DrawButton,
}

skin.button_highlight = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/selected_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	DrawControl     = DrawButton,
}

skin.action_button = {
	TileImageArrow       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/arrow.png",
	padding              = {10, 10, 10, 10},
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	DrawControl          = DrawButton,
}

skin.option_button = {
	TileImageArrow       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/arrow.png",
	padding              = {10, 10, 10, 10},
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	DrawControl          = DrawButton,
}

skin.negative_button = {
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {0.878, 0.251, 0.251, 1},
	DrawControl          = DrawButton,
}

skin.button_disabled = {
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.15},
	disabledColor        = {0.369, 0.369, 0.369, 1},
	DrawControl          = DrawButton,
}

skin.panel_button = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/panel_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	DrawControl     = DrawPanel,
}

skin.panel_button_rounded = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/panel_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	DrawControl     = DrawPanel,
}

skin.combobox = {
	TileImageArrow       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/arrow.png",
	padding              = {10, 10, 10, 10},
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.086, 0.086, 0.086, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	DrawControl          = DrawComboBox,
}

skin.combobox_window = {
	clone       = "window",
	color       = {1, 1, 1, 1},
	TileImage   = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/panel_bk.png",
	tiles       = {6, 34, 6, 6},
	padding     = {4, 3, 3, 4},
	borderColor = {1, 1, 1, 0.24},
}

skin.combobox_scrollpanel = {
	clone       = "scrollpanel",
	borderColor = {1, 1, 1, 0},
	padding     = {0, 0, 0, 0},
}

skin.combobox_item = {
	clone         = "button",
	borderColor   = {1, 1, 1, 0},
	focusColor    = {0.132, 0.132, 0.132, 1},
	selectedColor = {0.125, 0.125, 0.125, 1},
}

skin.checkbox = {
	TileImageBK       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/check_box.png",
	TileImageFG       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/check_tick.png",
	TileImageBK_round = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/check_box.png",
	TileImageFG_round = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/check_tick.png",
	tiles             = {3, 3, 3, 3},
	boxsize           = 13,
	focusColor        = {1, 1, 1, 1},
	textColor         = {0.839, 0.839, 0.839, 1},
	DrawControl       = DrawCheckbox,
}

skin.editbox = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	padding         = {10, 10, 10, 10},
	backgroundColor = {1, 1, 1, 0},
	focusColor      = {1, 1, 1, 0},
	borderColor     = {1, 1, 1, 0.24},
	cursorColor     = {1, 1, 1, 1},
	selectionColor  = {0.125, 0.125, 0.125, 1},
	DrawControl     = DrawEditBox,
}

skin.textbox = {
	TileImageBK     = ":cl:empty.png",
	TileImageFG     = ":cl:empty.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 0},
	borderColor     = {0, 0, 0, 0},
	focusColor      = {0, 0, 0, 0},
	selectionColor  = {0.125, 0.125, 0.125, 1},
	DrawControl     = DrawEditBox,
}

skin.imagelistview = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/sunken_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	DrawControl     = DrawBackground,
}

skin.imagelistviewitem = {
	TileImageBK     = ":cl:empty.png",
	TileImageFG     = ":cl:empty.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	focusColor      = {0.132, 0.132, 0.132, 1},
	selectedColor   = {0.125, 0.125, 0.125, 1},
}

skin.panel = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/panel_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	DrawControl     = DrawPanel,
}

skin.panel_internal = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/panel_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	DrawControl     = DrawPanel,
}

skin.panelSmall = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/panel_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	DrawControl     = DrawPanel,
}

skin.overlay_panel = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/panel_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	DrawControl     = DrawPanel,
}

skin.progressbar = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/sunken_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	color           = {0.816, 0.627, 0.125, 1},
	DrawControl     = DrawProgressbar,
}

skin.multiprogressbar = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/sunken_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	color           = {0.816, 0.627, 0.125, 1},
}

skin.scrollpanel = {
	BackgroundTileImage = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/sunken_bk.png",
	bkgndtiles          = {6, 34, 6, 6},
	BorderTileImage     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	bordertiles         = {6, 34, 6, 6},
	TileImage           = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/panel_bk.png",
	tiles               = {6, 34, 6, 6},
	htiles              = {6, 34, 6, 6},
	HTileImage          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/panel_bk.png",
	KnobTileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	HKnobTileImage      = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageBK         = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/sunken_bk.png",
	TileImageFG         = ":cl:empty.png",
	backgroundColor     = {1, 1, 1, 1},
	borderColor         = {1, 1, 1, 0.15},
	padding             = {5, 5, 5, 0},
	KnobColor           = {0.494, 0.494, 0.494, 1},
	KnobColorSelected   = {0.62, 0.62, 0.62, 1},
	DrawControl         = DrawScrollPanel,
}

skin.trackbar = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/sunken_bk.png",
	TileImageFG     = ":cl:empty.png",
	TileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/sunken_bk.png",
	TileImageV      = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/sunken_bk.png",
	KnobTileImage   = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	HTileImage      = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/sunken_bk.png",
	HKnobTileImage  = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	StepImage       = ":cl:empty.png",
	ThumbImage      = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	color           = {0.62, 0.62, 0.62, 1},
	DrawControl     = DrawTrackbar,
}

skin.treeview = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/sunken_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
}

skin.window = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	TileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	color           = {1, 1, 1, 0},
	padding         = {13, 13, 13, 13},
	captionColor    = {0.62, 0.62, 0.62, 1},
	DrawControl     = DrawWindow,
}

skin.main_window = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	TileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	color           = {1, 1, 1, 0},
	padding         = {13, 13, 13, 13},
	captionColor    = {0.62, 0.62, 0.62, 1},
	DrawControl     = DrawWindow,
}

skin.main_window_small = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	TileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	color           = {1, 1, 1, 0},
	padding         = {13, 13, 13, 13},
	captionColor    = {0.62, 0.62, 0.62, 1},
	DrawControl     = DrawWindow,
}

skin.main_window_small_tall = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	TileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	color           = {1, 1, 1, 0},
	padding         = {13, 13, 13, 13},
	captionColor    = {0.62, 0.62, 0.62, 1},
	DrawControl     = DrawWindow,
}

skin.main_window_small_flat = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	TileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	color           = {1, 1, 1, 0},
	padding         = {13, 13, 13, 13},
	captionColor    = {0.62, 0.62, 0.62, 1},
	DrawControl     = DrawWindow,
}

skin.main_window_small_very_flat = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	TileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	color           = {1, 1, 1, 0},
	padding         = {13, 13, 13, 13},
	captionColor    = {0.62, 0.62, 0.62, 1},
	DrawControl     = DrawWindow,
}

skin.main_window_tall = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	TileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	color           = {1, 1, 1, 0},
	padding         = {13, 13, 13, 13},
	captionColor    = {0.62, 0.62, 0.62, 1},
	DrawControl     = DrawWindow,
}

skin.window_black = {
	TileImageBK     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	TileImageFG     = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	borderColor     = {1, 1, 1, 0.15},
	TileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/window_bk.png",
	color           = {1, 1, 1, 0},
	padding         = {13, 13, 13, 13},
	captionColor    = {0.62, 0.62, 0.62, 1},
	DrawControl     = DrawWindow,
}

skin.line = {
	TileImage       = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 0.15},
	borderColor     = {1, 1, 1, 0.15},
	color           = {1, 1, 1, 0.15},
	DrawControl     = DrawLine,
}

skin.tabbar = {
	TileImageBK     = ":cl:empty.png",
	TileImageFG     = ":cl:empty.png",
	tiles           = {6, 34, 6, 6},
	backgroundColor = {1, 1, 1, 1},
	focusColor      = {0.132, 0.132, 0.132, 1},
	selectedColor   = {0.125, 0.125, 0.125, 1},
}

skin.tabbaritem = {
	TileImageBK          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/fill.png",
	TileImageFG          = ":c:LuaUI/Widgets/chili_old/Skins/ShiroGraphite/border_tab.png",
	tiles                = {6, 34, 6, 6},
	backgroundColor      = {0.051, 0.051, 0.051, 1},
	focusColor           = {0.132, 0.132, 0.132, 1},
	pressBackgroundColor = {0.178, 0.178, 0.178, 1},
	selectedColor        = {0.125, 0.125, 0.125, 1},
	borderColor          = {1, 1, 1, 0.24},
	padding              = {1, 1, 1, 2},
	DrawControl          = DrawTabBarItem,
}

skin.control = skin.general

return skin
